### PR TITLE
backends: change timestamp from int to datetime.timedelta

### PR DESCRIPTION
**Pull request by FFY00**
Per the discussion on #70.

Signed-off-by: Filipe Laíns <lains@riseup.net>

### CODE REVIEW

**Comment by FFY00** [comment]
I have only tested on the luna and usbmon backends. I'd appreciate if someone could test it on the usbproxy one, all the others are pretty straightforward so I am confident about the implementation there.

**Comment by Qyriad** [comment]
The LUNA backend seems to come up with some interesting timestamps with this pull request: 
luna_timestamps

Looks like the operands got flipped here: https://github.com/usb-tools/ViewSB/blob/0835252ec56c5ff7c8ba480fceeaf88f4a6ae534/viewsb/backends/luna.py#L92 :)

OpenVizsla timestamps also don't factor in rollover, though that's [nothing new](#31)
openvizsla_timestamps

**Comment by FFY00** [comment]
Oh, yes. I noticed this a few days ago but was too tired to update the PR :sweat_smile:

**Comment by FFY00** [comment]
> OpenVizsla timestamps also don't factor in rollover, though that's [nothing new](#31)

The link here is broken for me. Though it seems that is a pre-existing issue. I don't have any hardware to test it out, so we could merge this PR and then someone could open a new PR fixing that.

**Comment by Qyriad** [comment]
Oops, the link was meant to reference #31, but yeah in any case that's a separate issue. Thanks for the PR!

**Pull request merged**
