### PR TITLE
frontends.tui: add a hotkey that <c>lears the captured packets

### PR DESCRIPTION
**Pull request by whitequark**

### CODE REVIEW

**Comment by FFY00** [comment]
Hum, this is not working as expected here. Not sure if it is throwing an exception as we can't see that right now.

**Comment by whitequark** [comment]
Rebase issue. Moment.

**Comment by whitequark** [comment]
Nope, not a rebase issue, there's something wrong with my logic.

**Comment by whitequark** [comment]
Huh... this was the culprit:
```diff
     def remove_all_packets(self):
-        self._child_keys = []
         self.get_value().clear_packets()
+        self._child_keys = []
         self._invalidate()
```

**Comment by Qyriad** [comment]
So, for whatever reason, pressing `c` with some packets in the queue immediately crashes the tui, for me.

**Comment by whitequark** [comment]
Ah, I think I know the culprit; I'll take a look soonish.

**Comment by whitequark** [comment]
@Qyriad Fixed.

**Review by Qyriad — APPROVED** [review]

**Pull request merged**
